### ISSUE TITLE
Allow json input data if schema is specified as JSON

### ISSUE THREAD

**Issue by crphang** [kelindar/talaria#38]
Currently, if the specified schema for column is JSON and input is JSON, value will be marshaled twice and will not work.

https://github.com/kelindar/talaria/blob/6083b6ff0a6f3c3c56730eee262734b0b77afae0/internal/encoding/block/from_orc.go#L109

```go
// convertToJSON converts an ORC map/list/struct to JSON
func convertToJSON(value interface{}) (string, bool) {
	switch vt := value.(type) {
	case []orctype.MapEntry:
		remap := make(map[string]interface{}, len(vt))
		for _, v := range vt {
			remap[fmt.Sprintf("%v", v.Key)] = v.Value
		}
		value = remap
	case orctype.Struct:
	case []interface{}:
	case interface{}:
	default:
		return "", false
	}

	b, err := json.Marshal(value)
	if err != nil {
		return "", false
	}

	return string(json.RawMessage(b)), true
}
```

We can add support for the case where input is already json and ignore return accordingly.

**Comment by kelindar** [comment]
Indeed, I see. How would we check if it's already JSON? @crphang

**Comment by crphang** [comment]
I am playing with the thought that if input type is specified as orctype String and desired schema in Talaria is `json` , we can simply return with `value, true`.

There are two cases here:

1. If user specified json string input, but desired to be `json`, happy path.
1. If user specifies string input (which is not actually a json), but desired to be `json` we will miss out on a json marshalling here.

How bad is (2)?

Another option is using computed columns to decode and undo the effect of double marshalling

**Comment by kelindar** [comment]
Yeah I think it's not too bad. I wonder if we can have a quick estimator tho whether the string is actually JSON or not. For example, we could have a look at the first and last characters to see if it could be potentially valid JSON.
